### ISSUE TITLE
dev roadmap

### ISSUE THREAD

**Issue by PeterBreen** [PeterBreen/planefinder#1]
In short, build a quick prototype to make sure everything functions, then extend, extend, extend.

- [x] initial next setup (render a default next page)
- [x] fetch/render data from JSON (make sure app can render results based on data) 
- [x] build "detail page" (the 'answer' page which displays all info about a given model)
- [x] set up server.js routing for detail pages (see [this page](https://learnnextjs.com/basics/fetching-data-for-pages/fetching-data-for-pages), requires login)
- [ ] import external font properly (for newer browers, avoid FOUT with font-display: optional, see [CSS Tricks](https://css-tricks.com/really-dislike-fout-font-display-optional-might-jam/))
- [ ] build pick a/b function (saves answer in a format so I can check against planes.json)
- [ ] build answer function (takes data from a/b picks and returns best matched result)
- [ ] build "weather balloon" escape page (the "I give up!" default answer)

...at this point, the proto should be fully functional in terms of returning one of the 3 test case results, but it's still not done.

- [ ] based on example experience, refactor planes.json _structure_ and then add more models as _data_ once structure is finalized
- [ ] refactor style for consistency
- [ ] find ten million pub domain photos of planes, add to static directory, ref in data appropriately 
- [ ] test correct path for each model in data (images are correct for a/b pick, returned result is accurate) 
- [ ] test deliberately mismatched/incorrect paths, make sure those return weather balloons (right now they do _not_)

And eventually,
- [ ] deploy to production 
- [ ] also make sure to deploy as static HTML app using Next's export
- [ ] test in parallel, selectively enable/disable JS in browser, find out what breaks and where (and ideally, why)
